### ISSUE TITLE
make fail with error: error: unknown argument: '-no-opaque-pointers'

### ISSUE THREAD

**Issue by ysarasty** [splendiddata/session_variable#8]
Red Hat 9:

[postgres@localhost ~/extensions/session_variable]> cd session_variable/
[postgres@localhost ~/extensions/session_variable/session_variable]> ls
expected                        session_variable--2.0.control   session_variable--3.1--3.2.sql  session_variable--3.2.sql      session_variable.css   sql
LICENSE                         session_variable--2.0.sql       session_variable--3.1.control   session_variable--3.3.control  session_variable.h
Makefile                        session_variable--3.0--3.1.sql  session_variable--3.1.sql       session_variable--3.3.sql      session_variable.html
README.md                       session_variable--3.0.control   session_variable--3.2--3.3.sql  session_variable.c             session_variable.o
session_variable--2.0--3.0.sql  session_variable--3.0.sql       session_variable--3.2.control   session_variable.control       session_variable.so
[postgres@localhost ~/extensions/session_variable/session_variable]> make
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2  -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o session_variable.bc session_variable.c
error: unknown argument: '-no-opaque-pointers'
make: *** [/usr/pgsql-15/lib/pgxs/src/makefiles/../../src/Makefile.global:1094: session_variable.bc] Error 1

**Comment by M-Butter** [comment]
I do not have RedHat 9 yet, and at the moment I am quite busy. Please allow me some time to set up a new VM to see what is going ion here.

Regards,
Martin.

**Comment by M-Butter** [comment]
Apparently the -no-opaque-pointers is added by the configure action before the Postgres compilation. That option will be added if the clang version does support it.
Apparently your postgres has been compiled with a clang version that does support option -no-opaque-pointers, and now you try to compile session_variable with a clang version that does not support that option.
